[workspace]
members = [
    "latex2mmlc",
    "latex2mmlc_cli",
    "latex2mmlc_python",
    "latex2mmlc_wasm",
    "mathml_renderer",
]
exclude = [
    "fuzz"
]
default-members = ["latex2mmlc_cli"]
resolver = "2"

[workspace.package]
edition = "2021"
rust-version = "1.79"
license = "MIT"

[profile.dev.package]
insta.opt-level = 3
similar.opt-level = 3

[profile.release.package.latex2mmlc_wasm]
# Tell `rustc` to optimize for small code size.
opt-level = "s"

[profile.release]
lto = true
codegen-units = 1
